#!/bin/bash
clear
Menu() {
clear
    echo -e '\n'
    echo -e "    \e[05;33mDatami\e[05m \e[01;32m@EhisOpeNer\e[05m"
    echo -e "   \e[05;32mRaj, escolhe uma carta\e[05m"
    echo -e "\033[01;32mㅤㅤㅤ \e[0m\e[01;35mCole o pacote\e[00m"
read App
echo -e "\033[01;32mㅤㅤ \e[0m\e[1;36mCole a atividade\e[00m"
read atividade
echo ""
echo -e "\033[0m\033[01;31mㅤㅤㅤE lá vamos nós \033[05m"			
    connect
    }

connect () {
clear
am start -n $App/$atividade E1="sleep 4"
check() {
    vpn=$(ifconfig | grep -c tun0)
    case $vpn in
0) sleep 4 ; check;;
1) cp /data/data/$App/cache/android.conf /storage/emulated/0/Download/Neymar.ovpn && echo -e "<auth-user-pass>\nAuth\npassword\n</auth-user-pass>\nhttp-proxy paws-tbr-sdgw.datami.net 8043\n--verify-client-cert none" >> /storage/emulated/0/Download/Neymar.ovpn && termux-open --chooser /storage/emulated/0/Download/Neymar.ovpn --content-type "application/x-openvpn-profile"
esac
}
check
}
clear
Menu
